### ISSUE TITLE
Method [undoFlash] does not exist.

### ISSUE THREAD

**Issue by jeffochoa** [mpociot/reanimate#1]
i'm getting this error 

Method [undoFlash] does not exist.

using 

use \Mpociot\Reanimate\ReanimateModels;

**Comment by mpociot** [comment]
Could you provide some example code?

The usage should be like this: https://github.com/mpociot/reanimate/blob/develop/tests/controllers/UserController.php

**Comment by mpociot** [comment]
Do you still experience this issue?
